<?php
declare(strict_types=1);

namespace TanoWAF\WAFCore\Filter\Bidirectional;

/**
 * Implement compression the same way as the unix `compress` utility.
 * The algorithm is described at: https://ieeexplore.ieee.org/document/1659158
 * @license public domain. Code generated by AI
 */
class UnixCompressor
{
    // UNIX compress reserves code 256 for CLEAR (dictionary reset)
    const CLEAR_CODE = 256;
    const FIRST_FREE_CODE = 257;
    const MAX_BITS = 16;

    static array $compressDict = [];
    static array $uncompressDict = [];

    public static function compress(string $input): string
    {
        // 1. Initialize Header (UNIX .Z Magic Bytes)
        // 0x1F, 0x9D = Magic. 0x90 = 16-bit max, block compression (clear code enabled)
        $output = "\x1f\x9d\x90";

        /// @todo... check: this is what cli `compress` does. But does LZW mandate it, or should we return ''?
        if ($input === '') {
            return $output;
        }

        // 2. Initialize Dictionary
        $dict = self::initializeCompressDict();
        $nextCode = self::FIRST_FREE_CODE;
        $bitWidth = 9;
        $maxCodeForWidth = (1 << $bitWidth);
        $MAX_CODE = (1 << self::MAX_BITS);

        $currentPhrase = '';
        $rawCodes = [];

        // 3. Core Adaptive LZW Loop
        $len = strlen($input);
        for ($i = 0; $i < $len; $i++) {
            $char = $input[$i];
            $combined = $currentPhrase . $char;

            if (isset($dict[$combined])) {
                $currentPhrase = $combined;
            } else {
                $rawCodes[] = ['code' => $dict[$currentPhrase], 'width' => $bitWidth];

                if ($nextCode < $MAX_CODE) {
                    $dict[$combined] = $nextCode;
                    $nextCode++;

                    // Shift bit width when code limit is crossed
                    if ($nextCode > $maxCodeForWidth && $bitWidth < self::MAX_BITS) {
                        $bitWidth++;
                        $maxCodeForWidth = (1 << $bitWidth);
                    }
                } else {
                    // Dictionary is full. Pure UNIX compress issues a CLEAR code,
                    // flushes the dictionary, and drops back to 9-bit width.
                    $rawCodes[] = ['code' => self::CLEAR_CODE, 'width' => $bitWidth];

                    $dict = self::initializeCompressDict();
                    $nextCode = self::FIRST_FREE_CODE;
                    $bitWidth = 9;
                    $maxCodeForWidth = (1 << $bitWidth);
                }
                $currentPhrase = $char;
            }
        }

        if ($currentPhrase !== '') {
            $rawCodes[] = ['code' => $dict[$currentPhrase], 'width' => $bitWidth];
        }

        // 4. Variable-Width Bit-Packing Engine
        $bitBuffer = 0;
        $bitCount = 0;
        $bodyBytes = '';
        $totalBitsUsed = 0;

        foreach ($rawCodes as $item) {
            $code = $item['code'];
            $width = $item['width'];

            // Push values into the buffer (Little-Endian structure)
            $bitBuffer |= ($code << $bitCount);
            $bitCount += $width;
            $totalBitsUsed += $width;

            while ($bitCount >= 8) {
                $bodyBytes .= chr($bitBuffer & 0xFF);
                $bitBuffer >>= 8;
                $bitCount -= 8;
            }
        }

        // Flush remaining fragments
        if ($bitCount > 0) {
            $bodyBytes .= chr($bitBuffer & 0xFF);
        }

/// @todo... enable _but fix_ this logic (and the corresponding unpacking one) - it does not match what we get from cli `compress` !!
/*
        // 5. Apply the UNIX Block Alignment Padding Bug Requirement
        // UNIX uncompress expects data padded to multi-byte limits based on the final width.
        $expectedBytes = (int)ceil($totalBitsUsed / 8);
        $remainderBits = $totalBitsUsed % ($bitWidth * 8);

        if ($remainderBits > 0) {
            $paddingBitsNeeded = ($bitWidth * 8) - $remainderBits;
            $totalPaddedBytes = (int)ceil(($totalBitsUsed + $paddingBitsNeeded) / 8);
            $padBytesCount = $totalPaddedBytes - $expectedBytes;

            $bodyBytes .= str_repeat("\x00", $padBytesCount);
        }
*/
        return $output . $bodyBytes;
    }

    public static function uncompress(string $data): string|false
    {
        if ($data === '') {
            return '';
        }

        // 1. Verify Magic Header (0x1F, 0x9D)
        if (strlen($data) < 3 || !str_starts_with($data, "\x1f\x9d")) {
            //throw new \Exception("Invalid file format: Missing UNIX compress magic headers.");
            return false;
        }

        $headerFlags = ord($data[2]);
        $maxBits = $headerFlags & 0x1F; // Usually 16
        $blockMode = (bool)($headerFlags & 0x80); // Usually true (0x90)

        $body = substr($data, 3);
        $bodyLen = strlen($body);

        // 2. Initialize Dictionary
        $dict = self::initializeUnCompressDict();

        $MAX_CODE_LIMIT = (1 << $maxBits);

        $nextCode = self::FIRST_FREE_CODE;
        $bitWidth = 9;
        $maxCodeForWidth = (1 << $bitWidth);

        // Bit-extraction buffer setup
        $bitBuffer = 0;
        $bitCount = 0;
        $byteIdx = 0;

        $oldCode = null;
        $output = '';

        // 3. Core Decompression & Bit Shifting Loop
        while (true) {
            // Populate the bit buffer until we have enough bits for the current code width
            while ($bitCount < $bitWidth) {
                if ($byteIdx >= $bodyLen) {
                    break;
                }
                $bitBuffer |= (ord($body[$byteIdx]) << $bitCount);
                $bitCount += 8;
                $byteIdx++;
            }

            // If we ran out of bits and couldn't construct a full code, end stream
            if ($bitCount < $bitWidth) {
                break;
            }

            // Extract the code using the current bit mask
            $code = $bitBuffer & ((1 << $bitWidth) - 1);

            // --- Trail Padding Lookahead Filter ---
            // The UNIX compress padding alignment bug inserts null bytes at the end of the file.
            // If the extracted code is 0, and all remaining bits in the buffer and remaining
            // stream bytes are also 0, this is alignment garbage rather than valid source data.

/*
            if ($code === 0 && ($bitBuffer >> $bitWidth) === 0) {
                $isPadding = true;
                for ($k = $byteIdx; $k < $bodyLen; $k++) {
                    if (ord($body[$k]) !== 0) {
                        $isPadding = false;
                        break;
                    }
                }
                if ($isPadding) {
                    break; // Gracefully terminate execution without appending null bytes
                }
            }
*/

            // Consume bits out of the buffer
            $bitBuffer >>= $bitWidth;
            $bitCount -= $bitWidth;

            // Handle structural Block Mode Dictionary resets
            if ($blockMode && $code === self::CLEAR_CODE) {
                $dict = self::initializeUnCompressDict();
                $nextCode = self::FIRST_FREE_CODE;
                $bitWidth = 9;
                $maxCodeForWidth = (1 << $bitWidth);
                $oldCode = null;
                continue;
            }

            // First code processing step
            if ($oldCode === null) {
                if (!isset($dict[$code])) {
                    //throw new \Exception("Corrupted stream: Initial dictionary code lookup failed.");
                    return false;
                }
                $output .= $dict[$code];
                $oldCode = $code;
                continue;
            }

            // Standard LZW expansion logic (Includes handling the special KwKwK edge case)
            if (isset($dict[$code])) {
                $string = $dict[$code];
            } elseif ($code === $nextCode) {
                $string = $dict[$oldCode] . $dict[$oldCode][0];
            } else {
                //throw new \Exception("Corrupted stream: Decoded unassigned dictionary index code.");
                return false;
            }

            $output .= $string;

            // Dynamically track dictionary additions and bit width expansions
            if ($nextCode < $MAX_CODE_LIMIT) {
                $dict[$nextCode] = $dict[$oldCode] . $string[0];
                $nextCode++;

                // Shift width AFTER the threshold index value is mapped
                if ($nextCode >= $maxCodeForWidth && $bitWidth < $maxBits) {
                    $bitWidth++;
                    $maxCodeForWidth = (1 << $bitWidth);
                }
            }
            $oldCode = $code;
        }

        return $output;
    }

    protected static function initializeCompressDict(): array
    {
        if (! self::$compressDict) {
            for ($j = 0; $j < 256; $j++) {
                self::$compressDict[chr($j)] = $j;
            }
        }
        return self::$compressDict;
    }

    protected static function initializeUncompressDict(): array
    {
        if (! self::$uncompressDict) {
            for ($j = 0; $j < 256; $j++) {
                self::$uncompressDict[$j] = chr($j);
            }
        }
        return self::$uncompressDict;
    }
}
