WAF: {
  firewall {
    label: Firewall (Psr\\Http\\Server\\MiddlewareInterface)
    grid-columns: 1
  }
  proxy: {
    label: Proxy (Psr\\Http\\Server\\RequestHandlerInterface)
    grid-columns: 1
  }

  label: WAF (Psr\\Http\\Server\\RequestHandlerInterface)
  style.fill: "#DEE1EB"
}
