#!/bin/sh
### BEGIN INIT INFO
# Provides:          frankenphp
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Frankenphp web server
# Description:       Starts frankenphp using start-stop-daemon
### END INIT INFO

# Init.d service script for frankenphp on ubuntu/debian
#
# @todo in order to bind to privileged ports, it requires a call to `setcap 'cap_net_bind_service=+ep' /usr/bin/frankenphp`
#       Shall we add it in here? (or give a warning on FP start if this was not done?)
#
# Try to keep dirs/users aligned as much as possible to https://github.com/php/frankenphp/blob/main/package/debian/frankenphp.service,
# https://github.com/php/frankenphp/blob/main/package/alpine/frankenphp.openrc
#
# Env vars which can be set in /etc/default/frankenphp:
# DAEMON
# DAEMON_OPTS
# FRANKENPHP_CONFIG
# FRANKENPHP_GROUP
# FRANKENPHP_USER
# LOGFILE
# PIDFILE
# ULIMIT
# VERBOSE
# WORKING_DIR

DESC="Frankenphp httpd web server"
NAME=frankenphp
DAEMON=/usr/bin/$NAME
STOP_SCHEDULE=INT/5/QUIT/5/KILL/5
VERBOSE=no

# Include config defaults if available
if [ -r "/etc/default/$NAME" ]; then
    . "/etc/default/$NAME"
fi

test -x $DAEMON || exit 1

. /lib/lsb/init-functions

if [ -z "$FRANKENPHP_CONFIG" ]; then
    FRANKENPHP_CONFIG=/etc/frankenphp/Caddyfile
fi
if [ -z "$FRANKENPHP_USER" ]; then
    FRANKENPHP_USER="$NAME"
fi
if [ -z "$FRANKENPHP_GROUP" ]; then
    FRANKENPHP_GROUP="$FRANKENPHP_USER"
fi
if [ -z "$WORKING_DIR" ]; then
    WORKING_DIR="/var/lib/$FRANKENPHP_USER"
fi
if [ -z "$PIDFILE" ]; then
    PIDFILE="/run/$FRANKENPHP_USER/frankenphp.pid"
fi
if [ -z "$LOGFILE" ]; then
    LOGFILE="/var/log/$NAME/frankenphp.log"
fi

DAEMON_OPTS="--pidfile $PIDFILE --config $FRANKENPHP_CONFIG $DAEMON_OPTS"

if [ -n "$ULIMIT" ]; then
    # Set ulimit if it is set in /etc/default/frankenphp
    ulimit $ULIMIT
fi

setup_dirs() {
    if [ ! -d "$(dirname "$PIDFILE")" ]; then
        mkdir "$(dirname "$PIDFILE")"
    fi
    if [ "$(dirname "$PIDFILE")" = "/run/$FRANKENPHP_USER/" ]; then
        chown "$FRANKENPHP_USER:$FRANKENPHP_GROUP" "$(dirname "$PIDFILE")"
    else
        chgrp "$FRANKENPHP_GROUP" "$(dirname "$PIDFILE")"
        chmod g+w "$(dirname "$PIDFILE")"
    fi

    if [ ! -d "$(dirname "$LOGFILE")" ]; then
        mkdir "$(dirname "$LOGFILE")"
    fi
    # @todo do we need a chgrp+chmod here?
    if [ ! -f "$LOGFILE" ]; then
        touch "$LOGFILE"
    fi
    chown "$FRANKENPHP_USER:$FRANKENPHP_GROUP" "$LOGFILE"
    chmod 640 "$LOGFILE"

    if [ ! -d "$(dirname "$WORKING_DIR")" ]; then
        mkdir "$(dirname "$WORKING_DIR")"
    fi
    # @todo do we need a chgrp+chmod here?
}

# Start the daemon/service
#
# Returns:
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start() {
    setup_dirs

    #if pidofproc -p $PIDFILE "$DAEMON" > /dev/null 2>&1 ; then
    #    return 1
    #fi
    start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null \
        || return 1

    # @todo allow easy rotation of the log file by piping into multilog or similar, since frankenphp does not handle that via a signal
    start-stop-daemon --start --quiet -b -c "$FRANKENPHP_USER":"$FRANKENPHP_GROUP" -d "$WORKING_DIR" -O "$LOGFILE" \
        --exec $DAEMON -- run $DAEMON_OPTS 2>/dev/null \
        || return 2
}

# Test the configuration
test_config() {
    $DAEMON validate --config "$FRANKENPHP_CONFIG" >/dev/null 2>&1
}

# Returns:
#   0 if config was reloaded
#   2 if config could not be reloaded (eg. daemon not started)
do_reload() {
    # This returns 1 if FP is not running or presumably other errors
    $DAEMON reload --config "$FRANKENPHP_CONFIG" >/dev/null 2>&1 || return 2
}

# @todo in order to achieve this, we should pipe the caddy log into something like multilog...
#rotate_logs() {
#    # Rotate log files
#    start-stop-daemon --stop --signal USR1 --quiet --pidfile $PIDFILE --name $NAME
#    return 0
#}

# Returns:
#   0 if daemon has been stopped
#   1 if daemon was not running
#   2 if daemon could not be stopped
do_stop() {
    # see https://caddy.community/t/looking-for-linux-signal-handling-details-for-caddy/15406
    #if [ -z "$(pidofproc -p $PIDFILE $DAEMON)" ]; then
    #    return 1
    #fi
    #$DAEMON stop $DAEMON_OPTS >/dev/null 2>&1 || return 2

    start-stop-daemon --stop --retry="$STOP_SCHEDULE" --quiet --remove-pidfile --pidfile $PIDFILE --name $NAME
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop "$1"
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was not running"
                # exit 0 even if server was not running
                exit 0
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    status)
        status_of_proc -p $PIDFILE "$DAEMON" "$NAME"
        #exit $?
        ;;

    reload)
        log_daemon_msg "Reloading $DESC" "$NAME"
        do_reload
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                # @todo what does this message mean? Server _should_ have been running...
                #[ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0)
                        log_end_msg 0
                        ;;
                    1|*)
                        log_end_msg 1 # Old process is still or failed to running
                        exit 1
                        ;;
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    configtest)
        log_daemon_msg "Testing $DESC configuration"
        test_config
        log_end_msg $?
        ;;

    # @todo add a `rotate` action

    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|configtest}" >&2
        exit 3
        ;;
esac
