#!/bin/sh
### BEGIN INIT INFO
# Provides:          roadrunner
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Roadrunner web server
# Description:       Starts roadrunner using start-stop-daemon
### END INIT INFO

# Init.d service script for roadrunner on ubuntu/debian
#
# @todo in order to bind to privileged ports, it requires a call to `setcap 'cap_net_bind_service=+ep' /usr/bin/rr`
#       Shall we add it in here? (or give a warning on FP start if this was not done?)
#
# Env vars which can be set in /etc/default/roadrunner:
# DAEMON
# DAEMON_OPTS
# ROADRUNNER_CONFIG
# ROADRUNNER_GROUP
# ROADRUNNER_USER
# LOGFILE
# PIDFILE
# ULIMIT
# VERBOSE
# WORKING_DIR

DESC="Roadrunner httpd web server"
NAME=roadrunner
DAEMON=/usr/bin/rr
STOP_SCHEDULE=QUIT/5/KILL/5
VERBOSE=no

# Include config defaults if available
if [ -r "/etc/default/$NAME" ]; then
    . "/etc/default/$NAME"
fi

test -x $DAEMON || exit 1

. /lib/lsb/init-functions

if [ -z "$ROADRUNNER_CONFIG" ]; then
    ROADRUNNER_CONFIG=/etc/roadrunner/rr.yaml
fi
if [ -z "$ROADRUNNER_USER" ]; then
    ROADRUNNER_USER="$NAME"
fi
if [ -z "$ROADRUNNER_GROUP" ]; then
    ROADRUNNER_GROUP="$ROADRUNNER_USER"
fi
if [ -z "$WORKING_DIR" ]; then
    WORKING_DIR="/var/lib/$ROADRUNNER_USER"
fi
if [ -z "$PIDFILE" ]; then
    PIDFILE="/run/$ROADRUNNER_USER/roadrunner.pid"
fi
if [ -z "$LOGFILE" ]; then
    LOGFILE="/var/log/$NAME/roadrunner.log"
fi

DAEMON_OPTS="--config $ROADRUNNER_CONFIG --WorkDir $WORKING_DIR $DAEMON_OPTS"

if [ -n "$ULIMIT" ]; then
    # Set ulimit if it is set in /etc/default/roadrunner
    ulimit $ULIMIT
fi

setup_dirs() {
    if [ -n "$PIDFILE" ]; then
        if [ ! -d "$(dirname "$PIDFILE")" ]; then
            mkdir "$(dirname "$PIDFILE")"
        fi
        if [ "$(dirname "$PIDFILE")" = "/run/$ROADRUNNER_USER/" ]; then
            chown "$ROADRUNNER_USER:$ROADRUNNER_GROUP" "$(dirname "$PIDFILE")"
        else
            chgrp "$ROADRUNNER_GROUP" "$(dirname "$PIDFILE")"
            chmod g+w "$(dirname "$PIDFILE")"
        fi
    fi

    if [ -n "$LOGFILE" ]; then
        if [ ! -d "$(dirname "$LOGFILE")" ]; then
            mkdir "$(dirname "$LOGFILE")"
        fi
        # @todo do we need a chgrp+chmod here?
        if [ ! -f "$LOGFILE" ]; then
            touch "$LOGFILE"
        fi
        chown "$ROADRUNNER_USER:$ROADRUNNER_GROUP" "$LOGFILE"
        chmod 640 "$LOGFILE"
    fi

    if [ -n "$WORKING_DIR" ]; then
        if [ ! -d "$(dirname "$WORKING_DIR")" ]; then
            mkdir "$(dirname "$WORKING_DIR")"
        fi
        # @todo do we need a chgrp+chmod here?
    fi
}

# Start the daemon/service
#
# Returns:
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start() {
    setup_dirs

    #if pidofproc -p $PIDFILE "$DAEMON" > /dev/null 2>&1 ; then
    #    return 1
    #fi
    start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null \
        || return 1

    # @todo check: do we need to allow easy rotation of the log file by piping into multilog or similar, or does roadrunner handle that via a signal?
    # removed: -d "$WORKING_DIR"
    start-stop-daemon --start --quiet -c "$ROADRUNNER_USER":"$ROADRUNNER_GROUP" -b -O "$LOGFILE" --make-pidfile --pidfile "$PIDFILE" \
        --exec $DAEMON -- serve $DAEMON_OPTS 2>/dev/null \
        || return 2
}

# Returns:
#   0 if config was reloaded
#   2 if config could not be reloaded (eg. daemon not started)
do_reload() {
    ### @todo... send a signal SIGUSR2 to (restart the server and) reload the config - check if rr propagates it to php...
    ### # This returns 1 if FP is not running or presumably other errors
    ###$DAEMON reload --config "$ROADRUNNER_CONFIG" >/dev/null 2>&1 || return 2
    .
}

# @todo... check if we can send a signal to rotate the logs
#rotate_logs() {
#    # Rotate log files
#    start-stop-daemon --stop --signal USR1 --quiet --pidfile $PIDFILE --name $NAME
#    return 0
#}

# Returns:
#   0 if daemon has been stopped
#   1 if daemon was not running
#   2 if daemon could not be stopped
do_stop() {
    # see https://caddy.community/t/looking-for-linux-signal-handling-details-for-caddy/15406
    #if [ -z "$(pidofproc -p $PIDFILE $DAEMON)" ]; then
    #    return 1
    #fi
    #$DAEMON stop $DAEMON_OPTS >/dev/null 2>&1 || return 2

    start-stop-daemon --stop --retry="$STOP_SCHEDULE" --quiet --remove-pidfile --pidfile $PIDFILE --name $NAME
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop "$1"
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was not running"
                # exit 0 even if server was not running
                exit 0
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    status)
        status_of_proc -p $PIDFILE "$DAEMON" "$NAME"
        #exit $?
        ;;

    reload)
        log_daemon_msg "Reloading $DESC" "$NAME"
        do_reload
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                # @todo what does this message mean? Server _should_ have been running...
                #[ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0)
                        log_end_msg 0
                        ;;
                    1|*)
                        log_end_msg 1 # Old process is still or failed to running
                        exit 1
                        ;;
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    # @todo add a `rotate` action

    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload}" >&2
        exit 3
        ;;
esac
