#!/bin/sh
### BEGIN INIT INFO
# Provides:          swoole
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Swoole web server
# Description:       Starts swoole using start-stop-daemon
### END INIT INFO

# Init.d service script for swoole on ubuntu/debian
#
# No setcap for Swoole, as it would be a liability issue, given it uses the php executable
#
# Env vars which can be set in /etc/default/swoole_server:
# DAEMON
# DAEMON_OPTS
# ROADRUNNER_CONFIG
# SWOOLE_GROUP
# SWOOLE_USER
# LOGFILE
# PIDFILE
# SWOOLE_EXTENSION (either swoole or openswoole)
# ULIMIT
# VERBOSE
# VHOST
# WORKER_ARGS
# WORKER_SCRIPT
# WORKER_SCRIPT_DIR
# WORKING_DIR

DESC="Swoole httpd web server"
NAME=swoole
DAEMON=/usr/bin/swoole
PREPEND_FILE=/etc/swoole/prepend.php
STOP_SCHEDULE=INT/5/QUIT/5/KILL/5
SWOOLE_EXTENSION=openswoole
VERBOSE=no
VHOST=server
WORKER_SCRIPT=waf.php
WORKER_SCRIPT_DIR=/var/www/tests/public

# Include config defaults if available
if [ -r "/etc/default/${NAME}_${VHOST}" ]; then
    . "/etc/default/${NAME}_${VHOST}"
fi

test -x $DAEMON || exit 1

. /lib/lsb/init-functions

if [ -z "$SWOOLE_USER" ]; then
    SWOOLE_USER="$NAME"
fi
if [ -z "$SWOOLE_GROUP" ]; then
    SWOOLE_GROUP="$SWOOLE_USER"
fi
if [ -z "$WORKING_DIR" ]; then
    WORKING_DIR="/var/lib/$SWOOLE_USER"
fi
if [ -z "$PIDFILE" ]; then
    PIDFILE="/run/$SWOOLE_USER/swoole.pid"
fi
# @todo should we leave the log file to swoole_$vhost.json?
if [ -z "$LOGFILE" ]; then
    LOGFILE="/var/log/$NAME/${VHOST}.log"
fi
if [ -z "$WORKER_ARGS" ]; then
    WORKER_ARGS="/etc/swoole/swoole_${VHOST}.json $LOGFILE"
fi

# we use a php auto_prepend_file to set env vars that can be used by our worker for the log file, listening port
DAEMON_OPTS="-d auto_prepend_file=$PREPEND_FILE -f $WORKER_SCRIPT_DIR/$WORKER_SCRIPT $DAEMON_OPTS -- $WORKER_ARGS"

if [ -n "$ULIMIT" ]; then
    # Set ulimit if it is set in /etc/default/swoole
    ulimit $ULIMIT
fi

setup_dirs() {
    if [ -n "$PIDFILE" ]; then
        if [ ! -d "$(dirname "$PIDFILE")" ]; then
            mkdir "$(dirname "$PIDFILE")"
        fi
        if [ "$(dirname "$PIDFILE")" = "/run/$SWOOLE_USER/" ]; then
            chown "$SWOOLE_USER:$SWOOLE_GROUP" "$(dirname "$PIDFILE")"
        else
            chgrp "$SWOOLE_GROUP" "$(dirname "$PIDFILE")"
            chmod g+w "$(dirname "$PIDFILE")"
        fi
    fi

    if [ -n "$LOGFILE" ]; then
        if [ ! -d "$(dirname "$LOGFILE")" ]; then
            mkdir "$(dirname "$LOGFILE")"
        fi
        # @todo do we need a chgrp+chmod here?
        if [ ! -f "$LOGFILE" ]; then
            touch "$LOGFILE"
        fi
        chown "$SWOOLE_USER:$SWOOLE_GROUP" "$LOGFILE"
        chmod 640 "$LOGFILE"
    fi

    if [ -n "$WORKING_DIR" ]; then
        if [ ! -d "$(dirname "$WORKING_DIR")" ]; then
            mkdir "$(dirname "$WORKING_DIR")"
        fi
        # @todo do we need a chgrp+chmod here?
    fi
}

# Start the daemon/service
#
# Returns:
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start() {
    setup_dirs

    if "$DAEMON" -m 2>/dev/null | fgrep -q swoole 2>/dev/null; then
        PHP_OPTS="-dextension=$SWOOLE_EXTENSION $DAEMON_OPTS"
    else
        PHP_OPTS="$DAEMON_OPTS"
    fi

    #if pidofproc -p $PIDFILE "$DAEMON" > /dev/null 2>&1 ; then
    #    return 1
    #fi
# @todo...test:  this will most likely return true for _any_ php process running... either add `--pidfile` or move to using pidofproc
    start-stop-daemon --start --quiet --exec $DAEMON --test > /dev/null \
        || return 1

    start-stop-daemon --start --quiet -c "$SWOOLE_USER":"$SWOOLE_GROUP" -b -d "$WORKING_DIR" --make-pidfile --pidfile "$PIDFILE" \
        --exec $DAEMON -- serve $PHP_OPTS 2>/dev/null \
        || return 2
}

# Returns:
#   0 if config was reloaded
#   2 if config could not be reloaded (eg. daemon not started)
do_reload() {
    ### @todo... send a signal SIGHUP to (restart the server and) reload the config
    ### # This returns 1 if FP is not running or presumably other errors
    ###$DAEMON reload --config "$SWOOLE_CONFIG" >/dev/null 2>&1 || return 2
    .
}

# @todo... check if we can send a signal to rotate the logs
#rotate_logs() {
#    # Rotate log files
#    start-stop-daemon --stop --signal USR1 --quiet --pidfile $PIDFILE --name $NAME
#    return 0
#}

# Returns:
#   0 if daemon has been stopped
#   1 if daemon was not running
#   2 if daemon could not be stopped
do_stop() {
    start-stop-daemon --stop --retry="$STOP_SCHEDULE" --quiet --remove-pidfile --pidfile $PIDFILE --name $NAME
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$VHOST"
        do_start
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" "$VHOST"
        do_stop "$1"
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was not running"
                # exit 0 even if server was not running
                exit 0
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    status)
        status_of_proc -p $PIDFILE "$DAEMON" "$NAME"
        #exit $?
        ;;

    reload)
        log_daemon_msg "Reloading $DESC" "$VHOST"
        do_reload
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                # @todo what does this message mean? Server _should_ have been running...
                #[ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    restart)
        log_daemon_msg "Restarting $DESC" "$VHOST"
        do_stop stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0)
                        log_end_msg 0
                        ;;
                    1|*)
                        log_end_msg 1 # Old process is still or failed to running
                        exit 1
                        ;;
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    # @todo add a `rotate` action

    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload}" >&2
        exit 3
        ;;
esac
