#!/bin/sh
### BEGIN INIT INFO
# Provides:          swoole
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Swoole web server
# Description:       Starts swoole using start-stop-daemon
### END INIT INFO

# Init.d service script for swoole on ubuntu/debian
#
# No setcap for Swoole, as it would be a liability issue, given it uses the php executable
#
# In order to allow this file to be used to start different services, create symlinks to it, named `swoole_<vhost>`,
# and use `swoole_<vhost>` as name of the service to start/stop.
#
# That will automatically drive all further config: the `/etc/default/swoole_<vhost>` file which can optionally be used
# to alter configs, the name of the php script that swoole will run, defaulting to <vhost>_swoole.php
# and the json file used to set configs for the Swoole server instance: /etc/swoole/swoole_<vhost>.json
#
# Env vars which can be set in /etc/default/swoole_<vhost>:
# DAEMON
# DAEMON_OPTS
# LOGFILE
# PIDFILE
# PREPEND_FILE
# SWOOLE_CONFIG (not in use atm)
# SWOOLE_GROUP
# SWOOLE_USER
# SWOOLE_EXTENSION (either swoole or openswoole)
# ULIMIT
# VERBOSE
# VHOST
# WORKER_ARGS
# WORKER_SCRIPT
# WORKER_SCRIPT_DIR
# WORKING_DIR

DESC="Swoole web server"
NAME=swoole
DAEMON=/usr/bin/swoole
PREPEND_FILE=/etc/swoole/prepend.php
SWOOLE_EXTENSION=swoole
VERBOSE=no
VHOST=server
WORKER_SCRIPT_DIR=/var/www/tests/public

# @todo initialize VHOST to an empty string, and allow it to be passed in as 2nd argument, to allow usage without
#       the need for symlinks
INIT_SCRIPT_NAME="$0"
if echo "$INIT_SCRIPT_NAME" | grep -F -q '_'; then
    # @todo split on 1st underscore, not last
    VHOST="$(echo "$INIT_SCRIPT_NAME" | sed 's/.*_//')"
fi

# Include config defaults if available
if [ -r "/etc/default/${NAME}_${VHOST}" ]; then
    . "/etc/default/${NAME}_${VHOST}"
fi

if [ -z "$VHOST" ]; then exit 1; fi

test -x $DAEMON || exit 1

. /lib/lsb/init-functions

if [ -z "$SWOOLE_USER" ]; then
    SWOOLE_USER="$NAME"
fi
if [ -z "$SWOOLE_GROUP" ]; then
    SWOOLE_GROUP="$SWOOLE_USER"
fi
if [ -z "$WORKING_DIR" ]; then
    WORKING_DIR="/var/lib/$SWOOLE_USER"
fi
if [ -z "$PIDFILE" ]; then
    PIDFILE="/run/$SWOOLE_USER/${NAME}_${VHOST}.pid"
fi
if [ -z "$LOGFILE" ]; then
    LOGFILE="/var/log/${NAME}/${VHOST}.log"
fi
if [ -z "$WORKER_SCRIPT" ]; then
    WORKER_SCRIPT="${VHOST}_${NAME}.php"
fi
if [ -z "$WORKER_ARGS" ]; then
    WORKER_ARGS="/etc/${NAME}/${NAME}_${VHOST}.json ${VHOST}"
fi

# we use a php auto_prepend_file to set env vars that can be used by our worker
# @todo it would be nice to be able to have the $WORKER_SCRIPT_DIR/$WORKER_SCRIPT value be set in the json file,
#       as we do for RoadRunner and FrankenPHP, but there is a bootstrap issue: we need to know the php script name
#       to build the command line used here. We could maybe use jq to achieve that, but it seems hackish...
D_OPTS=''
if [ -n "$PREPEND_FILE" ]; then
    D_OPTS="-d auto_prepend_file=$PREPEND_FILE "
fi
DAEMON_OPTS="$D_OPTS-f $WORKER_SCRIPT_DIR/$WORKER_SCRIPT $DAEMON_OPTS -- $WORKER_ARGS"

if [ -n "$ULIMIT" ]; then
    # Set ulimit if it is set in /etc/default/swoole
    ulimit $ULIMIT
fi

setup_dirs() {
    if [ -n "$PIDFILE" ]; then
        if [ ! -d "$(dirname "$PIDFILE")" ]; then
            mkdir "$(dirname "$PIDFILE")"
        fi
        if [ "$(dirname "$PIDFILE")" = "/run/$SWOOLE_USER/" ]; then
            chown "$SWOOLE_USER:$SWOOLE_GROUP" "$(dirname "$PIDFILE")"
        else
            chgrp "$SWOOLE_GROUP" "$(dirname "$PIDFILE")"
            chmod g+w "$(dirname "$PIDFILE")"
        fi
    fi

    if [ -n "$LOGFILE" ]; then
        if [ ! -d "$(dirname "$LOGFILE")" ]; then
            mkdir "$(dirname "$LOGFILE")"
        fi
        # @todo do we need a chgrp+chmod here?
        if [ ! -f "$LOGFILE" ]; then
            touch "$LOGFILE"
        fi
        chown "$SWOOLE_USER:$SWOOLE_GROUP" "$LOGFILE"
        chmod 640 "$LOGFILE"
    fi

    if [ -n "$WORKING_DIR" ]; then
        if [ ! -d "$(dirname "$WORKING_DIR")" ]; then
            mkdir "$(dirname "$WORKING_DIR")"
        fi
        # @todo do we need a chgrp+chmod here?
    fi
}

# Start the daemon/service
#
# Returns:
#   0 if daemon has been started
#   1 if daemon was already running
#   2 if daemon could not be started
do_start() {
    setup_dirs

    if "$DAEMON" -m 2>/dev/null | fgrep -q swoole 2>/dev/null; then
        PHP_OPTS="$DAEMON_OPTS"
    else
        PHP_OPTS="-d extension=$SWOOLE_EXTENSION $DAEMON_OPTS"
    fi

    if pidofproc -p $PIDFILE "$DAEMON" > /dev/null 2>&1 ; then
        return 1
    fi
    # this seems to return true for _any_ php/swoole process running...
    #start-stop-daemon --start --quiet --make-pidfile --pidfile "$PIDFILE" --exec $DAEMON --test > /dev/null \
    #    || return 1

    # @todo allow easy rotation of the log file by piping into multilog or similar (we prefer not to use swoole's own logger
    #       as it misses logging errors happening before $server->start()))
    # @todo check if option `daemonize` is valid for both swoole and openswoole. If it is, test using that instead of `-b` here
    start-stop-daemon --start --quiet -b -c "$SWOOLE_USER":"$SWOOLE_GROUP" -d "$WORKING_DIR" -O "$LOGFILE" --make-pidfile --pidfile "$PIDFILE" \
        --exec $DAEMON -- $PHP_OPTS 2>/dev/null \
        || return 2
}

# NB: this does not seem to reliably force Swoole to pick up code changes from disk...
# Returns:
#   0 if config was reloaded
#   1 if config could not be reloaded because daemon not started
do_reload() {
    start-stop-daemon --stop --signal USR1 --quiet --pidfile $PIDFILE
}

# @todo... check if we can send a signal to rotate the logs
#rotate_logs() {
#    # Rotate log files
#    # removed `--name $NAME`, as there can be many `swoole` processes running at any given time
#    start-stop-daemon --stop --signal USR1 --quiet --pidfile $PIDFILE
#    return 0
#}

# Returns:
#   0 if daemon has been stopped
#   1 if daemon was not running
#   2 if daemon could not be stopped
do_stop() {
    # removed `--name $NAME`, as there can be many `swoole` processes running at any given time
    start-stop-daemon --stop --signal TERM --quiet --remove-pidfile --pidfile $PIDFILE
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$VHOST"
        do_start
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was already running"
                # exit 0 even if server was already running
                exit 0
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" "$VHOST"
        do_stop "$1"
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was not running"
                # exit 0 even if server was not running
                exit 0
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    status)
        # /lib/lsb/init-functions uses $name (arg 2) only for informational messages
        status_of_proc -p $PIDFILE "$DAEMON" "$NAME"
        #exit $?
        ;;

    reload)
        log_daemon_msg "Reloading $DESC" "$VHOST"
        do_reload
        RET_STATUS=$?
        case "$RET_STATUS" in
            0|1)
                log_end_msg 0
                [ "$VERBOSE" != no ] && [ $RET_STATUS = 1 ] && log_warning_msg "Server was not running"
                exit 0
                ;;
            2)
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    restart)
        log_daemon_msg "Restarting $DESC" "$VHOST"
        do_stop stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0)
                        log_end_msg 0
                        exit 0
                        ;;
                    1|*)
                        log_end_msg 1 # Old process is still or failed to running
                        exit 1
                        ;;
                esac
                ;;
            *)
                # Failed to stop
                log_end_msg 1
                exit 1
                ;;
        esac
        ;;

    # @todo add a `rotate` action

    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload}" >&2
        exit 3
        ;;
esac
